# Generated by Django 4.2.1 on 2023-05-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0002_usuario_alter_pedido_cliente_alter_pedido_vendedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
