# Generated by Django 4.2.1 on 2023-05-26 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grup1', '0004_alter_detalle_idpedido_datosusuarioextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='detalle',
            name='idpedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grup1.pedido'),
        ),
        migrations.DeleteModel(
            name='DatosUsuarioExtra',
        ),
    ]
