# Generated by Django 4.2.1 on 2023-05-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0005_usuario_alter_detalle_idpedido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
