# Generated by Django 4.2.1 on 2023-05-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='precio',
            field=models.IntegerField(default=50),
        ),
    ]
