# Generated by Django 4.2.1 on 2023-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0007_pedido_stock_alter_detalle_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
