# Generated by Django 4.2.1 on 2023-05-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0008_remove_pedido_stock_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=50),
        ),
    ]
