# Generated by Django 4.2.1 on 2023-06-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup1', '0009_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
